### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by ashfand-s-simformsolutions** [baddymaster/torrent-hound#5]
import cfscrape as cfs
  File "/home/ashfand/Desktop/torrent/env/lib/python3.8/site-packages/cfscrape/__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'

**Comment by baddymaster** [comment]
There is a known bug with the compatibility of the latest version of this package. Try using `requests==2.28.2` instead.
